### PR TITLE
Added badges of Travis, Codeclimate and Codecov

### PR DESCRIPTION
**Pull request by hrishikesh-dahiya**
## Description
 - Travis CI, Codecov, Codeclimate badges are added to the README.md
 - Updated the links to Contributing Guidelines and Wiki page in README.md
 - .travis.yml updated with python3.5 (from the previous python2.7)

## Motivation
 - It gives the badges of Travis CI, Codecov, Codeclimate on the README.md page
 - For the correct link to the Wiki page of the repository
 - python3.5 used in the technology stack
 
 ## Types of changes
- [x] Badges are shown in README.md
- [x] Links corrected in README.md
- [x] .travis.yml updated

## Notify reviewers
@rohangoel96 @achyudhk

### CODE REVIEW

**Comment by rohangoel96** [comment]
@hrishikesh-dahiya please use setup your email and name on bash. https://help.github.com/articles/setting-your-commit-email-address-in-git/
Also follow the PR template

**Comment by hrishikesh-dahiya** [comment]
Another commit is added for the updated links in the README.md. Should they be squashed to one? (They serve a little bit different purpose)

**Comment by rohangoel96** [comment]
I think they both serve the same purpose: both fixing link issues arising due to change in ownership

**Comment by hrishikesh-dahiya** [comment]
the .travis.yml also updated and commits squashed to one

**Comment by rohangoel96** [comment]
@hrishikesh-dahiya your commit is still isn't properly linked your account.
c52700

**Comment by hrishikesh-dahiya** [comment]
i think the account linking problem is solved now

**Comment by achyudhk** [comment]
@hrishikesh-dahiya I have merged your pull request. Please note that you commit messages must be in an imperative tone: **Add** badges of Travis, Codeclimate and Codecov, and not **Added**

**Comment by achyudhk** [comment]
Thanks for the contribution

**Pull request merged**
