### PR TITLE
Add SlackArchive data fetcher

### PR DESCRIPTION
**Pull request by achyudhk**
## Description
 - The SlackArchive data fetcher addresses the _downloading logs from slackarchive.io_ story (Issue #31)
 - Fixes the incorrect .gitignore file that did not allow tracking of lib folder

## Motivation
 - This is necessary for creating the dataset for the analysis

## Example usage
```
    team_data = fetch_team('kubernetes')
    channels = fetch_channels('kubernetes', team_data['team_id'])
    for channel in channels:
        if channel['name'] == 'multi-platform':
            messages = fetch_messages('kubernetes', team_data['team_id'], channel['channel_id'], 100, 0)
    print(messages)
```
 
 ## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checks
 - [x] Squash your commits down to one, or a few, discreet changesets before submitting a pull request
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/2.x/.github/CONTRIBUTING.md)
 - [x] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [x] If possible, include an example in the description, that could help all readers (including project members) to get a better picture of the change
 - [x] Avoid other runtime dependencies unless abslutely necessary 
 - [x] Rebase your commit history so that each commit is meaningful and states the intention behind the change 
 - [x] Ensure that your pull request follows the [style guidelines](https://github.com/rohangoel96/Slack-Community-Analysis-Tool/wiki/Coding-Guidelines)
 - [x] Mention `Fixes #<story number>` in the description _if relevant_
 - [x] At least one commit should mention `Fixes #<issue number>` _if relevant_

## Notify reviewers
@rohangoel96 @prasadtalasila

### CODE REVIEW

**Comment by achyudhk** [comment]
@DeveloperCAP/scat-core Someone create a relevant story for this. I was not able to find any.

**Comment by hrishikesh-dahiya** [comment]
def fetch_messages(domain, team_id, channel_id, size, offset): <br>
by convention, there should not be more than for arguments in a function, so the codeclimate build is not passing, also we need unit tests and documentation to fulfill the requirements of the issue

**Comment by achyudhk** [comment]
I disagree with the convention and it's counterproductive. Don't remember seeing it on PEP8 which is what in following.

**Comment by achyudhk** [comment]
Thanks for the user story @hrishikesh-dahiya, I'll link it now.

**Comment by achyudhk** [comment]
Tests added. Someone review and merge this ASAP.

**Pull request merged**
